version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '8080:8080'
      - '5000:5000'
    env_file:
      - '.env'
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ipc: host
