# set the base image to Debian
# https://hub.docker.com/_/debian/
FROM ubuntu:16.04

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# and install dependencies
RUN apt-get update \
    && apt-get install -y curl \
    && apt-get -y autoclean

# nvm environment variables
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 12.16.1

# install nvm
# https://github.com/creationix/nvm#install-script
RUN curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash

# install node and npm
RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# add node and npm to path so the commands are available
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# confirm installation
RUN node -v
RUN npm -v

# Install webpack dev server
RUN npm install webpack -g

# Working directory for application
WORKDIR /usr/src/app

# add cypress https://www.cypress.io/ to image.. ( slow install, avoid downloading it at each build )
# Ensure version in package.json is the same as the version in install-cypress.sh
COPY scripts/install-cypress.sh /usr/src/app/
RUN ./install-cypress.sh && npm install
RUN rm ./install-cypress.sh
