# set the base image to Node
FROM cypress/browsers:node14.16.0-chrome89-ff77

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

ENV CLIENT demo

# avoid million NPM install messages
ENV npm_config_loglevel warn

# start-and-serve (cypress) needs this installed globally
RUN npm install serve -g

COPY ./cypress/asound.conf /etc/

# Working directory for application
WORKDIR /usr/src/app

# yarn install into WORKDIR
COPY package.json ./
RUN npm install

# copy webapp files to container
COPY . .

CMD npm run start $CLIENT
