export const AUTH_TOKEN = 'AUTH_TOKEN'
export const IMPERSONATED_AUTH_TOKEN = 'IMPERSONATED_AUTH_TOKEN'
export const NO_CUSTOM_BANNER = 'NO_CUSTOM_BANNER'
export const OAUTH_REDIRECT_ROUTE = 'OAUTH_REDIRECT_ROUTE'